GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/68766c4f1f5c0490483d5fb0

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jo",
  "number": "39-99801238190"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "39-99801238190"
}